# Generated by Django 6.0.1 on 2026-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("guestcount", models.IntegerField()),
                ("reservation_time", models.DateField(auto_now=True)),
                ("comments", models.CharField(max_length=250)),
            ],
        ),
    ]
